- name: Install apt packages
  ansible.builtin.apt:
    name:
      - antiword
      - autoconf
      - automake
      - bison
      - bzip2
      - ca-certificates
      - default-jre-headless
      - ffmpeg
      - flac
      - flex
      - g++
      - gawk
      - gettext
      - git
      - lame
      - libcgi-pm-perl
      - libglib2.0-dev
      - libicu-dev
      - libjpeg-dev
      - libmad0
      - libsox-fmt-mp3
      - libtool
      - libxml2-dev
      - libxslt1-dev
      - lighttpd
      - make
      - pkgconf
      - poppler-utils
      - pstotext
      - python3
      - python3-dev
      - python3-docx
      - python3-lxml
      - python3-networkx
      - python3-openpyxl
      - python3-pip
      - python3-requests
      - sox
      - swig
      - tesseract-ocr
      - unrtf
      - unzip

- name: Install Python packages
  ansible.builtin.pip:
    break_system_packages: true
    name:
      - scipy # the ubuntu package is conflicting with the numpy version there
      - numpy
      - torch
      - textract
      - twol # for ofitwol
      - matplotlib # the ubuntu package is conflicting with the numpy version

- name: Configure lighttpd block
  block:
    - name: Read IP block list
      ansible.builtin.include_vars: ip_block_list.yaml
    - name: Install lighttpd configuration file
      ansible.builtin.template:
        src: templates/lighttpd.conf.j2
        dest: /etc/lighttpd/lighttpd.conf
    - name: Restart lighttpd
      ansible.builtin.systemd_service:
        name: lighttpd.service
        state: restarted

- name: Ensure directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: www-data
    group: www-data
  loop:
    - /var/www/cgi-bin
    - /var/www/tmp
    - /var/www/anee
    - /var/www/resources
    - /var/log/kielipankki-tools
    - /usr/local/share/histner
    - /usr/local/share/ofitwol
    - /usr/local/share/transducers

- name: Set /var/www ownership
  ansible.builtin.file:
    owner: www-data
    group: www-data
    recurse: true
    path: /var/www
