---
anee_package_names:
  - anee-lexical-portal-pmi-proper-2022-05
  - anee-lexical-portal-pmi-2022-05
  - anee-lexical-portal-pmi-non-proper-2022-05
  - anee-portal-second-millennium-2022-05
  - anee-portal-second-millennium-non-proper-2022-05
  - anee-portal-second-millennium-proper-2022-05
  - anee-portal-first-millennium-2022-05
  - anee-portal-first-millennium-non-proper-2022-05
  - anee-portal-first-millennium-proper-2022-05
  - anee-portal-neo-assyrian-all-2022-05
  - anee-portal-neo-assyrian-all-non-proper-2022-05
  - anee-portal-neo-assyrian-all-proper-2022-05
  - anee-portal-neo-assyrian-neo-assyrian-2022-05
  - anee-portal-neo-assyrian-neo-assyrian-non-proper-2022-05
  - anee-portal-neo-assyrian-neo-assyrian-proper-2022-05
  - anee-portal-neo-assyrian-standard-babylonian-2022-05
  - anee-portal-neo-assyrian-standard-babylonian-non-proper-2022-05
  - anee-portal-neo-assyrian-standard-babylonian-proper-2022-05
  - anee-lexical-portal-pmi-2022-05-swapped
  - anee-lexical-portal-pmi-non-proper-2022-05-swapped
  - anee-portal-second-millennium-2022-05-swapped
  - anee-portal-second-millennium-non-proper-2022-05-swapped
  - anee-portal-second-millennium-proper-2022-05-swapped
  - anee-portal-first-millennium-2022-05-swapped
  - anee-portal-first-millennium-non-proper-2022-05-swapped
  - anee-portal-first-millennium-proper-2022-05-swapped
  - anee-portal-neo-assyrian-all-2022-05-swapped
  - anee-portal-neo-assyrian-all-non-proper-2022-05-swapped
  - anee-portal-neo-assyrian-all-proper-2022-05-swapped
  - anee-portal-neo-assyrian-neo-assyrian-2022-05-swapped
  - anee-portal-neo-assyrian-neo-assyrian-non-proper-2022-05-swapped
  - anee-portal-neo-assyrian-neo-assyrian-proper-2022-05-swapped
  - anee-portal-neo-assyrian-standard-babylonian-2022-05-swapped
  - anee-portal-neo-assyrian-standard-babylonian-non-proper-2022-05-swapped
  - anee-portal-neo-assyrian-standard-babylonian-proper-2022-05-swapped
