---

- name: Create Pouta VM
  ansible.builtin.import_playbook: pouta-vm.yml

- name: Setup demo endpoint
  hosts: kielipankki-demo-vm
  become: true
  roles:
    - demo-setup
#    - firewall

- name: Build content
  hosts: kielipankki-demo-vm
  become: true
  roles:
    - html
    - cgi-bin
